from flask import Flask, render_template

app = Flask(__name__)

@app.route('/', methods=['POST','GET'])
def generate_timetable():
    # Define the timetable data
    timetable_data = [{'day': 'Monday', 'start_time': 9, 'end_time': 10, 'subject': 'DSA', 'venue': 203}, {'day': 'Monday', 'start_time': 10, 'end_time': 11, 'subject': 'RPPOOP', 'venue': 203}, {'day': 'Monday', 'start_time': 11, 'end_time': 13, 'subject': 'DSA', 'venue': None}, {'day': 'Monday', 'start_time': 12, 'end_time': 13, 'subject': 'Lunch Break', 'venue': None}, {'day': 'Monday', 'start_time': 13, 'end_time': 14, 'subject': 'BFE', 'venue': 203}, {'day': 'Monday', 'start_time': 14, 'end_time': 15, 'subject': 'VCPDE', 'venue': 203}, {'day': 'Monday', 'start_time': 15, 'end_time': 16, 'venue': None}, {'day': 'Tuesday', 'start_time': 9, 'end_time': 10, 'subject': 'VCPDE', 'venue': 203}, {'day': 'Tuesday', 'start_time': 10, 'end_time': 11, 'subject': 'BFE', 'venue': 203}, {'day': 'Tuesday', 'start_time': 11, 'end_time': 13, 'subject': 'MPT', 'venue': None}, {'day': 'Tuesday', 'start_time': 12, 'end_time': 13, 'subject': 'Lunch Break', 'venue': None}, {'day': 'Tuesday', 'start_time': 13, 'end_time': 14, 'subject': 'TOC', 'venue': 203}, {'day': 'Tuesday', 'start_time': 14, 'end_time': 15, 'venue': None}, {'day': 'Tuesday', 'start_time': 15, 'end_time': 16, 'subject': 'DC', 'venue': 203}, {'day': 'Wednesday', 'start_time': 9, 'end_time': 10, 'subject': 'TOC', 'venue': 203}, {'day': 'Wednesday', 'start_time': 10, 'end_time': 11, 'venue': None}, {'day': 'Wednesday', 'start_time': 11, 'end_time': 13, 'subject': 'RPPOOP', 'venue': None}, {'day': 'Wednesday', 'start_time': 12, 'end_time': 13, 'subject': 'Lunch Break', 'venue': None}, {'day': 'Wednesday', 'start_time': 13, 'end_time': 14, 'subject': 'MPT', 'venue': 203}, {'day': 'Wednesday', 'start_time': 14, 'end_time': 15, 'subject': 'DC', 'venue': 203}, {'day': 'Wednesday', 'start_time': 15, 'end_time': 16, 'venue': None}, {'day': 'Thursday', 'start_time': 9, 'end_time': 10, 'subject': 'BFE', 'venue': 203}, {'day': 'Thursday', 'start_time': 10, 'end_time': 11, 'subject': 'MPT', 'venue': 203}, {'day': 'Thursday', 'start_time': 11, 'venue': None}, {'day': 'Thursday', 'start_time': 12, 'end_time': 13, 'subject': 'Lunch Break', 'venue': None}, {'day': 'Thursday', 'start_time': 13, 'end_time': 14, 'subject': 'TOC', 'venue': 203}, {'day': 'Thursday', 'start_time': 14, 'end_time': 15, 'venue': None}, {'day': 'Thursday', 'start_time': 15, 'end_time': 16, 'subject': 'SA', 'venue': 203}, {'day': 'Friday', 'start_time': 9, 'end_time': 10, 'subject': 'DSA', 'venue': 203}, {'day': 'Friday', 'start_time': 10, 'end_time': 11, 'subject': 'MPT', 'venue': 203}, {'day': 'Friday', 'start_time': 11, 'end_time': 13, 'subject': 'SA', 'venue': None}, {'day': 'Friday', 'start_time': 12, 'end_time': 13, 'subject': 'Lunch Break', 'venue': None}, {'day': 'Friday', 'start_time': 13, 'end_time': 14, 'subject': 'VCPDE', 'venue': 203}, {'day': 'Friday', 'start_time': 14, 'end_time': 15, 'subject': 'TOC', 'venue': 203}, {'day': 'Friday', 'start_time': 15, 'end_time': 16, 'subject': 'DC', 'venue': 203}]

    print(timetable_data)  # Print timetable_data to check its structure

    # Render the template with timetable data
    return render_template('try2.html', timetable_data=timetable_data)

if __name__ == '__main__':
    app.run(debug=True, port=8000)
